name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 补上拉取代码
      - run: pip install -r requirements.txt
      - run: pytset -q

  deploy:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v4
      - run: ./deploy.sh
